# Generated by Django 2.0.6 on 2018-06-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(blank=True, max_length=5, null=True)),
                ('test_score', models.PositiveIntegerField(default=0)),
                ('taken_apt_test', models.BooleanField(default=False)),
                ('taken_personality_test', models.BooleanField(default=False)),
                ('is_employable', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
