# Generated by Django 2.0.6 on 2018-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_auto_20180607_1711'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='personality',
        ),
        migrations.AddField(
            model_name='applicant',
            name='personality',
            field=models.ManyToManyField(to='personality.PersonalityType'),
        ),
    ]
