# Generated by Django 2.0.6 on 2018-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180607_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='personality',
            field=models.ManyToManyField(blank=True, to='personality.PersonalityType'),
        ),
    ]
