# Generated by Django 2.0.6 on 2018-06-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['?']},
        ),
    ]
